name: api

on:
  push:
    branches: 
      - 'main'
      - 'staging'
env:
  REPO_URL: "anhkhoa3010"   #sjc.vultrcr.com/rome"
  SERVICE_NAME: "api"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      commit_hash: ${{ steps.build-image.outputs.COMMIT_HASH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build and push image
        id: build-image
        run: |
          commit_hash=$(git rev-parse --short $GITHUB_SHA)
          docker build -t ${REPO_URL}/${SERVICE_NAME}:${commit_hash} -t ${REPO_URL}/${SERVICE_NAME}:${{ github.ref_name }}-latest api
          echo "${{ secrets.dockerhub_pass }}" | docker login -u anhkhoa3010 -p --password-stdin
          docker push ${REPO_URL}/${SERVICE_NAME}:${commit_hash}
          docker push ${REPO_URL}/${SERVICE_NAME}:${{ github.ref_name }}-latest
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build 
    env:
      COMMIT_HASH: ${{ needs.build.outputs.commit_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "nakhoa3010/helm-charts.git"
          path: helm-charts
          ref: main
      - run: |
          NAMESPACE="x-oracle"
          HOST="api.x-oracle.com"
          if [[ ${{ github.ref_name }} == "staging" ]]; then
            HOST="staging-${HOST}"
            NAMESPACE="staging-${NAMESPACE}"
          fi
          helm upgrade --install ${SERVICE_NAME} helm-charts -f values.yaml -n ${NAMESPACE} \
            --set image.tag=${COMMIT_HASH} \
            --set ingress.hosts[0]=${HOST} \
            --create-namespace
